-   repo: https://github.com/thoughtworks/talisman
    rev: 'v1.28.0'  # Update me!
    hooks:
    # either `commit` or `push` support
    # -   id: talisman-push
    - id: talisman-commit
      entry: cmd --githook pre-commit